name: Deploy CD (Protected)

on:
  workflow_dispatch:
    inputs:
      trigger_password:
        description: 'Enter deployment password'
        required: true
        type: string

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
